//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Output_Model
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Ts { get; set; }
        public Nullable<int> Years { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Q127_100 { get; set; }
        public Nullable<int> Q127_150 { get; set; }
        public Nullable<int> Q127_220 { get; set; }
        public Nullable<int> Q127_330 { get; set; }
        public Nullable<int> Q127_470 { get; set; }
        public Nullable<int> A127_R47 { get; set; }
        public Nullable<int> A127_1R0 { get; set; }
        public Nullable<int> A127_1R5 { get; set; }
        public Nullable<int> A127_2R2 { get; set; }
        public Nullable<int> A127_3R3 { get; set; }
        public Nullable<int> A127_4R7 { get; set; }
        public Nullable<int> A127_6R8 { get; set; }
        public Nullable<int> A127_8R2 { get; set; }
        public Nullable<int> A127_100 { get; set; }
        public Nullable<int> A127_150 { get; set; }
        public Nullable<int> A127_220 { get; set; }
        public Nullable<int> A127_330 { get; set; }
        public Nullable<int> A127_470 { get; set; }
        public Nullable<int> A127_680 { get; set; }
        public Nullable<int> A127_820 { get; set; }
        public Nullable<int> A127_101 { get; set; }
        public Nullable<int> A127_151 { get; set; }
        public Nullable<int> A127_221 { get; set; }
        public Nullable<int> A127_331 { get; set; }
        public Nullable<int> A127_471 { get; set; }
        public Nullable<int> A127_681 { get; set; }
        public Nullable<int> A127_821 { get; set; }
        public Nullable<int> A127_102 { get; set; }
        public Nullable<int> A125_R47 { get; set; }
        public Nullable<int> A125_1R0 { get; set; }
        public Nullable<int> A125_1R5 { get; set; }
        public Nullable<int> A125_2R2 { get; set; }
        public Nullable<int> A125_3R3 { get; set; }
        public Nullable<int> A125_4R7 { get; set; }
        public Nullable<int> A125_6R8 { get; set; }
        public Nullable<int> A125_8R2 { get; set; }
        public Nullable<int> A125_100 { get; set; }
        public Nullable<int> A125_150 { get; set; }
        public Nullable<int> A125_220 { get; set; }
        public Nullable<int> A125_330 { get; set; }
        public Nullable<int> A125_470 { get; set; }
        public Nullable<int> A125_680 { get; set; }
        public Nullable<int> A125_820 { get; set; }
        public Nullable<int> A125_101 { get; set; }
        public Nullable<int> A125_151 { get; set; }
        public Nullable<int> A125_221 { get; set; }
        public Nullable<int> A125_331 { get; set; }
        public Nullable<int> A125_471 { get; set; }
        public Nullable<int> A125_681 { get; set; }
        public Nullable<int> A125_821 { get; set; }
        public Nullable<int> A125_102 { get; set; }
        public Nullable<int> A124_R47 { get; set; }
        public Nullable<int> A124_1R0 { get; set; }
        public Nullable<int> A124_1R5 { get; set; }
        public Nullable<int> A124_2R2 { get; set; }
        public Nullable<int> A124_3R3 { get; set; }
        public Nullable<int> A124_4R7 { get; set; }
        public Nullable<int> A124_6R8 { get; set; }
        public Nullable<int> A124_8R2 { get; set; }
        public Nullable<int> A124_100 { get; set; }
        public Nullable<int> A124_150 { get; set; }
        public Nullable<int> A124_220 { get; set; }
        public Nullable<int> A124_330 { get; set; }
        public Nullable<int> A124_470 { get; set; }
        public Nullable<int> A124_680 { get; set; }
        public Nullable<int> A124_820 { get; set; }
        public Nullable<int> A124_101 { get; set; }
        public Nullable<int> A124_151 { get; set; }
        public Nullable<int> A124_221 { get; set; }
        public Nullable<int> A124_331 { get; set; }
        public Nullable<int> A124_471 { get; set; }
        public Nullable<int> A124_681 { get; set; }
        public Nullable<int> A124_821 { get; set; }
        public Nullable<int> A124_102 { get; set; }
        public Nullable<int> Q127_100_NG { get; set; }
        public Nullable<int> Q127_150_NG { get; set; }
        public Nullable<int> Q127_220_NG { get; set; }
        public Nullable<int> Q127_330_NG { get; set; }
        public Nullable<int> Q127_470_NG { get; set; }
        public Nullable<int> A127_R47_NG { get; set; }
        public Nullable<int> A127_1R0_NG { get; set; }
        public Nullable<int> A127_1R5_NG { get; set; }
        public Nullable<int> A127_2R2_NG { get; set; }
        public Nullable<int> A127_3R3_NG { get; set; }
        public Nullable<int> A127_4R7_NG { get; set; }
        public Nullable<int> A127_6R8_NG { get; set; }
        public Nullable<int> A127_8R2_NG { get; set; }
        public Nullable<int> A127_100_NG { get; set; }
        public Nullable<int> A127_150_NG { get; set; }
        public Nullable<int> A127_220_NG { get; set; }
        public Nullable<int> A127_330_NG { get; set; }
        public Nullable<int> A127_470_NG { get; set; }
        public Nullable<int> A127_680_NG { get; set; }
        public Nullable<int> A127_820_NG { get; set; }
        public Nullable<int> A127_101_NG { get; set; }
        public Nullable<int> A127_151_NG { get; set; }
        public Nullable<int> A127_221_NG { get; set; }
        public Nullable<int> A127_331_NG { get; set; }
        public Nullable<int> A127_471_NG { get; set; }
        public Nullable<int> A127_681_NG { get; set; }
        public Nullable<int> A127_821_NG { get; set; }
        public Nullable<int> A127_102_NG { get; set; }
        public Nullable<int> A125_R47_NG { get; set; }
        public Nullable<int> A125_1R0_NG { get; set; }
        public Nullable<int> A125_1R5_NG { get; set; }
        public Nullable<int> A125_2R2_NG { get; set; }
        public Nullable<int> A125_3R3_NG { get; set; }
        public Nullable<int> A125_4R7_NG { get; set; }
        public Nullable<int> A125_6R8_NG { get; set; }
        public Nullable<int> A125_8R2_NG { get; set; }
        public Nullable<int> A125_100_NG { get; set; }
        public Nullable<int> A125_150_NG { get; set; }
        public Nullable<int> A125_220_NG { get; set; }
        public Nullable<int> A125_330_NG { get; set; }
        public Nullable<int> A125_470_NG { get; set; }
        public Nullable<int> A125_680_NG { get; set; }
        public Nullable<int> A125_820_NG { get; set; }
        public Nullable<int> A125_101_NG { get; set; }
        public Nullable<int> A125_151_NG { get; set; }
        public Nullable<int> A125_221_NG { get; set; }
        public Nullable<int> A125_331_NG { get; set; }
        public Nullable<int> A125_471_NG { get; set; }
        public Nullable<int> A125_681_NG { get; set; }
        public Nullable<int> A125_821_NG { get; set; }
        public Nullable<int> A125_102_NG { get; set; }
        public Nullable<int> A124_R47_NG { get; set; }
        public Nullable<int> A124_1R0_NG { get; set; }
        public Nullable<int> A124_1R5_NG { get; set; }
        public Nullable<int> A124_2R2_NG { get; set; }
        public Nullable<int> A124_3R3_NG { get; set; }
        public Nullable<int> A124_4R7_NG { get; set; }
        public Nullable<int> A124_6R8_NG { get; set; }
        public Nullable<int> A124_8R2_NG { get; set; }
        public Nullable<int> A124_100_NG { get; set; }
        public Nullable<int> A124_150_NG { get; set; }
        public Nullable<int> A124_220_NG { get; set; }
        public Nullable<int> A124_330_NG { get; set; }
        public Nullable<int> A124_470_NG { get; set; }
        public Nullable<int> A124_680_NG { get; set; }
        public Nullable<int> A124_820_NG { get; set; }
        public Nullable<int> A124_101_NG { get; set; }
        public Nullable<int> A124_151_NG { get; set; }
        public Nullable<int> A124_221_NG { get; set; }
        public Nullable<int> A124_331_NG { get; set; }
        public Nullable<int> A124_471_NG { get; set; }
        public Nullable<int> A124_681_NG { get; set; }
        public Nullable<int> A124_821_NG { get; set; }
        public Nullable<int> A124_102_NG { get; set; }
    }
}
